name: Get data from airtable every hour
on:
  schedule:
    - cron: "45 * * * *"

jobs:
  get-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install chrome and run
        run: |
          sudo apt-get -yqq update
          sudo apt-get -yqq install chromium-browser
          npm install
          npm run start
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        working-directory: public
      - name: Commit updates
        uses: EndBug/add-and-commit@v4
        with:
          author_name: test
          author_email: test@example.com
          message: "Update all.csv"
          add: "*.csv"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
